run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - golint
    - staticcheck
    - gosimple
    - unused
    - errcheck
    - goconst
    - gofmt
    - ineffassign
    - deadcode
    - structcheck
    - varcheck
    - misspell